# Generated by Django 2.2.9 on 2021-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210626_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='Описание группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default='Адрес группы', max_length=72),
        ),
    ]
