# Generated by Django 2.2.6 on 2021-08-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210802_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['pk']},
        ),
    ]
